output "certificate" {
  description = "The CA certificate generated by the module."
  value = {
    certificate = local.is_deployment_workspace ? tls_self_signed_cert.this[0].cert_pem : null
    base64      = local.is_deployment_workspace ? base64encode(tls_self_signed_cert.this[0].cert_pem) : null
  }
}

output "key" {
  description = "The CA key generated by the module."
  value = {
    certificate = local.is_deployment_workspace ? tls_private_key.this[0].private_key_pem : null
    base64      = local.is_deployment_workspace ? base64encode(tls_private_key.this[0].private_key_pem) : null
  }
}